name: Auto Deploy after push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Deploy to S3 bucket
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [14.15.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Npm install
        run: npm install

      - name: .env setting
        run: |
          echo "REACT_APP_API_KEY=${{secrets.REACT_APP_API_KEY}}" >> .env        
          echo "REACT_APP_API_KEY=${{secrets.REACT_APP_AUTH_DOMAIN}}" >> .env
          echo "REACT_APP_API_KEY=${{secrets.REACT_APP_PROJECT_ID}}" >> .env
          echo "REACT_APP_API_KEY=${{secrets.REACT_APP_STORAGE_BUCKET}}" >> .env
          echo "REACT_APP_API_KEY=${{secrets.REACT_APP_MESSAGING_SENDER_ID}}" >> .env
          echo "REACT_APP_API_KEY=${{secrets.REACT_APP_MEASUREMENT_ID}}" >> .env
          echo "REACT_APP_API_KEY=${{secrets.REACT_APP_BASEURL}}" >> .env
          echo "REACT_APP_API_KEY=${{secrets.REACT_APP_BASE_DOMAIN}}" >> .env
          echo "REACT_APP_API_KEY=${{secrets.REACT_APP_ACCESS_KEY_ID}}" >> .env
          echo "REACT_APP_API_KEY=${{secrets.REACT_APP_SECRET_ACCESS_KEY}}" >> .env
          echo "REACT_APP_API_KEY=${{secrets.REACT_APP_BUCKET}}" >> .env
          echo "REACT_APP_API_KEY=${{secrets.REACT_APP_REGION}}" >> .env

      - name: Build
        run: npm run build

      - name: Transfer to S3 for serving static
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.REGION }}
          SOURCE_DIR: 'dist'
